name: Test std::string

on:
  workflow_dispatch:

jobs:
  make-test:
    name: Make Test
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
        cl /std:c++14 /MD /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O2 /DNDEBUG /Zi main.cpp /link /machine:x64 /INCREMENTAL:NO
        main
        rmdir /S /Q .git

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Test Build
        path: .
