name: Build vc-temp-string-bug

on:
  workflow_dispatch:

jobs:
  make-test:
    name: Build vc-temp-string-bug
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # /std:c++14 
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
        cl /c /W3 /Zi /Gm- /O2 /Oi /D "_CRT_SECURE_NO_WARNINGS" /D "NOMINMAX" /GR /MD /EHsc /Fdmake-temp-string make-temp-string.cpp
        lib /MACHINE:X64 /OUT:make-temp-string.lib make-temp-string.obj
        del /Q make-temp-string.obj
        rmdir /S /Q .git

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: vc-temp-string-bug
        path: .
