name: Build temp string bug

on:
  workflow_dispatch:

jobs:
  make-test:
    name: Make Test
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # /std:c++14 
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall" x64
        cl /c /W3 /Zc:wchar_t /Zi /Gm- /O2 /Zc:inline /external:W0 /D "NDEBUG" /D "NOMINMAX" /GR /MD /EHsc make-temp-string.cpp
        lib /MACHINE:X64 /OUT:make-temp-string.lib make-temp-string.obj
        rmdir /S /Q .git

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: Test Build
        path: .
